name: Build and Deploy Astro Site with Bun

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 安装依赖
        run: bun install

      - name: 构建项目
        run: bun run build

      - name: 设置 SSH 密钥
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: 推送到服务器
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: 22
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/*"
          target: "${{ secrets.SERVER_TARGET_PATH }}"
          overwrite: true
          strip_components: 1
